/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/icenowy/git-repos/bfcpu/al_ip/d_mem_elf2_v1_bram.v
 ** Date	:	2019 04 06
 ** TD version	:	4.4.433
\************************************************************/

`timescale 1ns / 1ps

module d_mem_elf2_v1_bram ( doa, dia, addra, clka, wea, rsta );

	output [7:0] doa;

	input  [7:0] dia;
	input  [5:0] addra;
	input  wea;
	input  clka;
	input  rsta;




	EF2_LOGIC_BRAM #( .DATA_WIDTH_A(8),
				.ADDR_WIDTH_A(6),
				.DATA_DEPTH_A(64),
				.DATA_WIDTH_B(8),
				.ADDR_WIDTH_B(6),
				.DATA_DEPTH_B(64),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({8{1'b0}}),
				.addra(addra),
				.addrb({6{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(wea),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule